# Generated by Django 3.2.11 on 2022-01-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('shelter_name', models.CharField(max_length=100)),
                ('shelter_type', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
