# Generated by Django 3.2.11 on 2022-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='rating',
            field=models.FloatField(),
        ),
    ]
